# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import gs_gateway_pb2 as gs__gateway__pb2


class GsGatewayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Invoke = channel.unary_unary(
                '/pb.GsGateway/Invoke',
                request_serializer=gs__gateway__pb2.InvokeServiceRequest.SerializeToString,
                response_deserializer=gs__gateway__pb2.Message.FromString,
                )
        self.List = channel.unary_unary(
                '/pb.GsGateway/List',
                request_serializer=gs__gateway__pb2.Empty.SerializeToString,
                response_deserializer=gs__gateway__pb2.Functions.FromString,
                )
        self.Deploy = channel.unary_unary(
                '/pb.GsGateway/Deploy',
                request_serializer=gs__gateway__pb2.CreateFunctionRequest.SerializeToString,
                response_deserializer=gs__gateway__pb2.Message.FromString,
                )
        self.Delete = channel.unary_unary(
                '/pb.GsGateway/Delete',
                request_serializer=gs__gateway__pb2.DeleteFunctionRequest.SerializeToString,
                response_deserializer=gs__gateway__pb2.Message.FromString,
                )
        self.Update = channel.unary_unary(
                '/pb.GsGateway/Update',
                request_serializer=gs__gateway__pb2.CreateFunctionRequest.SerializeToString,
                response_deserializer=gs__gateway__pb2.Message.FromString,
                )
        self.GetMeta = channel.unary_unary(
                '/pb.GsGateway/GetMeta',
                request_serializer=gs__gateway__pb2.FunctionRequest.SerializeToString,
                response_deserializer=gs__gateway__pb2.Function.FromString,
                )
        self.GetLog = channel.unary_unary(
                '/pb.GsGateway/GetLog',
                request_serializer=gs__gateway__pb2.FunctionRequest.SerializeToString,
                response_deserializer=gs__gateway__pb2.Message.FromString,
                )
        self.ReplicaUpdate = channel.unary_unary(
                '/pb.GsGateway/ReplicaUpdate',
                request_serializer=gs__gateway__pb2.ScaleServiceRequest.SerializeToString,
                response_deserializer=gs__gateway__pb2.Message.FromString,
                )
        self.Info = channel.unary_unary(
                '/pb.GsGateway/Info',
                request_serializer=gs__gateway__pb2.Empty.SerializeToString,
                response_deserializer=gs__gateway__pb2.Message.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/pb.GsGateway/HealthCheck',
                request_serializer=gs__gateway__pb2.Empty.SerializeToString,
                response_deserializer=gs__gateway__pb2.Message.FromString,
                )


class GsGatewayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Invoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deploy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicaUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GsGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=gs__gateway__pb2.InvokeServiceRequest.FromString,
                    response_serializer=gs__gateway__pb2.Message.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=gs__gateway__pb2.Empty.FromString,
                    response_serializer=gs__gateway__pb2.Functions.SerializeToString,
            ),
            'Deploy': grpc.unary_unary_rpc_method_handler(
                    servicer.Deploy,
                    request_deserializer=gs__gateway__pb2.CreateFunctionRequest.FromString,
                    response_serializer=gs__gateway__pb2.Message.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=gs__gateway__pb2.DeleteFunctionRequest.FromString,
                    response_serializer=gs__gateway__pb2.Message.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=gs__gateway__pb2.CreateFunctionRequest.FromString,
                    response_serializer=gs__gateway__pb2.Message.SerializeToString,
            ),
            'GetMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMeta,
                    request_deserializer=gs__gateway__pb2.FunctionRequest.FromString,
                    response_serializer=gs__gateway__pb2.Function.SerializeToString,
            ),
            'GetLog': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLog,
                    request_deserializer=gs__gateway__pb2.FunctionRequest.FromString,
                    response_serializer=gs__gateway__pb2.Message.SerializeToString,
            ),
            'ReplicaUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicaUpdate,
                    request_deserializer=gs__gateway__pb2.ScaleServiceRequest.FromString,
                    response_serializer=gs__gateway__pb2.Message.SerializeToString,
            ),
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=gs__gateway__pb2.Empty.FromString,
                    response_serializer=gs__gateway__pb2.Message.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=gs__gateway__pb2.Empty.FromString,
                    response_serializer=gs__gateway__pb2.Message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.GsGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GsGateway(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.GsGateway/Invoke',
            gs__gateway__pb2.InvokeServiceRequest.SerializeToString,
            gs__gateway__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.GsGateway/List',
            gs__gateway__pb2.Empty.SerializeToString,
            gs__gateway__pb2.Functions.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Deploy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.GsGateway/Deploy',
            gs__gateway__pb2.CreateFunctionRequest.SerializeToString,
            gs__gateway__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.GsGateway/Delete',
            gs__gateway__pb2.DeleteFunctionRequest.SerializeToString,
            gs__gateway__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.GsGateway/Update',
            gs__gateway__pb2.CreateFunctionRequest.SerializeToString,
            gs__gateway__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.GsGateway/GetMeta',
            gs__gateway__pb2.FunctionRequest.SerializeToString,
            gs__gateway__pb2.Function.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.GsGateway/GetLog',
            gs__gateway__pb2.FunctionRequest.SerializeToString,
            gs__gateway__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReplicaUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.GsGateway/ReplicaUpdate',
            gs__gateway__pb2.ScaleServiceRequest.SerializeToString,
            gs__gateway__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.GsGateway/Info',
            gs__gateway__pb2.Empty.SerializeToString,
            gs__gateway__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.GsGateway/HealthCheck',
            gs__gateway__pb2.Empty.SerializeToString,
            gs__gateway__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
