apiVersion: v1
kind: Pod
metadata:
  name: simple
  labels:
    migPod: simple
  annotations:
    migrationProcess: "checkpoint"
    snapshotImgPath: "/mnt/shared_sheepfs/savedState"
spec:
  containers:
  - name: count
    image: alpine
    command: ["/bin/ash", "-c", "i=1; while true; do echo $i; i=$((i+1)); sleep 1; done"]
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "128Mi"
        cpu: "600m"
  nodeSelector:
    kubernetes.io/hostname: kubeetri1