apiVersion: v1
kind: Service
metadata:
  name: SERVICE-NAME
spec:
  selector:
    app: POD-NAME
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: NodePort

---
apiVersion: v1
kind: Pod
metadata:
  name: POD-NAME
  labels:
    app: POD-NAME
spec:
  containers:
  - name: POD-NAME
    image: dockereyes/get-hostname
    resources:
      limits:
        cpu: "5"
      requests:
        cpu: "3"  
    ports:
    - containerPort: 5000