# permissions for end users to edit livmigrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: livmigration-editor-role
rules:
- apiGroups:
  - gedgemig.etri.re.kr
  resources:
  - livmigrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gedgemig.etri.re.kr
  resources:
  - livmigrations/status
  verbs:
  - get
