# permissions for end users to view livmigrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: livmigration-viewer-role
rules:
- apiGroups:
  - gedgemig.etri.re.kr
  resources:
  - livmigrations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gedgemig.etri.re.kr
  resources:
  - livmigrations/status
  verbs:
  - get
