apiVersion: v1
kind: ServiceAccount
metadata:
  name: gedge-most-requested-policy-account
  namespace: gedge-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gedge-most-requested-policy-scheduler-role-binding
subjects:
- kind: ServiceAccount
  name: gedge-most-requested-policy-account
  namespace: gedge-system
roleRef:
  kind: ClusterRole
  name: admin 
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gedge-system
  name: gedge-most-requested-policy-dep
spec:
  selector:
    matchLabels:
      app: gedge-most-requested-policy
  replicas: 1
  template:
    metadata:
      labels:
        app: gedge-most-requested-policy
    spec:
      serviceAccount: gedge-most-requested-policy-account
      containers:
      - name: gedge-most-requested-policy-container
        image: dockereyes/gedge-most-requested-policy
        ports:
        - containerPort: 5000