
DB_NAME = "G_EDGE_YOLO"
YOLO_COLLECTION_NAME = "G_EDGE_YOLO_COL"

DB_NAME2 = "G_EDGE_YOLO_FIN"
YOLO_COLLECTION_NAME2 = "G_EDGE_YOLO_COL_FIN"

LIFE_CYCLE_ENQUEUE = "ENQUEUE"
LIFE_CYCLE_PREPROCESSING = "PREPROCESSING"
LIFE_CYCLE_PREPROCESSING_COMPLETE = "PREPROCESSING_COMPLETE"
LIFE_CYCLE_INFERENCING = "INFERENCING"
LIFE_CYCLE_INFERENCING_COMPLETE = "INFERENCING_COMPLETE"
LIFE_CYCLE_POSTPROCESSING = "POSTPROCESSING"
LIFE_CYCLE_EXIT = "EXIT"
LIFE_CYCLE_FINISHED = "FIN"

FAIL_COUNT = 4




