apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: gedge-system
spec:
  type: LoadBalancer
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
