apiVersion: v1
kind: ServiceAccount
metadata:
  name: gedge-gsch-server-account
  namespace: gedge-system-scheduler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gedge-gsch-server-role
rules:
- apiGroups: ['rbac.authorization.k8s.io']
  resources: ['clusterroles','clusterrolebindings']
  verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gedge-gsch-server-role-binding
subjects:
- kind: ServiceAccount
  name: gedge-gsch-server-account
  namespace: gedge-system-scheduler
roleRef:
  kind: ClusterRole
  name: gedge-gsch-server-role
  apiGroup: ""  
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gedge-gsch-server-node-role
rules:
- apiGroups: ['']
  resources: ['services','nodes','nodes/status']
  verbs: ['list','get','watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gedge-gsch-server-node-role-binding
subjects:
- kind: ServiceAccount
  name: gedge-gsch-server-account
  namespace: gedge-system-scheduler
roleRef:
  kind: ClusterRole
  name: gedge-gsch-server-node-role
  apiGroup: ""    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gedge-gsch-server-admin-role-binding
subjects:
- kind: ServiceAccount
  name: gedge-gsch-server-account
  namespace: gedge-system-scheduler
roleRef:
  kind: ClusterRole
  name: admin 
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: gedge-gsch-server-pod
  namespace: gedge-system-scheduler
  labels:
    app: gedge-gsch-server
spec:
  serviceAccount: gedge-gsch-server-account
  containers:
  - name: gedge-gsch-server-container
    image: dockereyes/gedge-gsch-server
    env:
    - name: API_GATEWAY_HOST
      valueFrom:
        configMapKeyRef:
          name: gedge-system-scheduler-configmap
          key: api-gateway-host
    - name: API_GATEWAY_PORT
      valueFrom:
        configMapKeyRef:
          name: gedge-system-scheduler-configmap
          key: api-gateway-port
    ports:
    - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: gedge-gsch-server-service
  namespace: gedge-system-scheduler
spec:
  type: NodePort
  selector:
    app: gedge-gsch-server
  ports:
    - protocol: TCP
      port: 8787
      targetPort: 8787
      nodePort: 32424
