apiVersion: v1
kind: ServiceAccount
metadata:
  name: gedge-platform-info-account
  namespace: gedge-system-scheduler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gedge-platform-node-role
rules:
- apiGroups: [""]
  resources: ["nodes","nodes/status"]
  verbs: ["list","get","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gedge-platform-node-role-binding
subjects:
- kind: ServiceAccount
  name: gedge-platform-info-account
  namespace: gedge-system-scheduler
roleRef:
  kind: ClusterRole
  name: gedge-platform-node-role
  apiGroup: ""    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gedge-platform-info-role
rules:
- apiGroups: ['rbac.authorization.k8s.io']
  resources: ['clusterrolebindings']
  verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gedge-platform-info-role-binding
subjects:
- kind: ServiceAccount
  name: gedge-platform-info-account
  namespace: gedge-system-scheduler
roleRef:
  kind: ClusterRole
  name: gedge-platform-info-role
  apiGroup: ""  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gedge-platform-info-admin-role-binding
subjects:
- kind: ServiceAccount
  name: gedge-platform-info-account
  namespace: gedge-system-scheduler
roleRef:
  kind: ClusterRole
  name: admin 
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: gedge-platform-info-pod
  namespace: gedge-system-scheduler
  labels:
    app: gedge-platform-info
spec:
  serviceAccount: gedge-platform-info-account
  containers:
  - name: gedge-platform-info-container
    image: dockereyes/gedge-platform-info
    env:
    - name: API_GATEWAY_HOST
      valueFrom:
        configMapKeyRef:
          name: gedge-system-scheduler-configmap
          key: api-gateway-host
    - name: API_GATEWAY_PORT
      valueFrom:
        configMapKeyRef:
          name: gedge-system-scheduler-configmap
          key: api-gateway-port
    ports:
    - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: gedge-platform-info-service
  namespace: gedge-system-scheduler
spec:
  type: NodePort
  selector:
    app: gedge-platform-info
  ports:
    - protocol: TCP
      port: 8787
      targetPort: 8787
      nodePort: 31414
