apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploytest
  labels:
    app: dptest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dptest
  template:
    metadata:
      labels:
        app: dptest
    spec:
      containers:
      - name: dptestnginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
