apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-scheduler-cluster-agent
  namespace: gedge-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-scheduler-cluster-agent-role-binding
subjects:
- kind: ServiceAccount
  name: custom-scheduler-cluster-agent
  namespace: gedge-system
roleRef:
  kind: ClusterRole
  name: admin 
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: custom-scheduler-cluster-agent
  namespace: gedge-system
spec:
  serviceAccount: custom-scheduler-cluster-agent
  containers:
  - name: custom-scheduler-cluster-agent
    image: dockereyes/custom-scheduler-cluster-agent
    ports:
    - containerPort: 5000
