apiVersion: v1
kind: ServiceAccount
metadata:
  name: gedge-front-server-account
  namespace: gedge-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gedge-front-server-role
rules:
- apiGroups: ['rbac.authorization.k8s.io']
  resources: ['clusterrolebindings']
  verbs: ['create', 'delete', 'deletecollection', 'get', 'list', 'patch', 'update', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gedge-front-server-role-binding
subjects:
- kind: ServiceAccount
  name: gedge-front-server-account
  namespace: gedge-system
roleRef:
  kind: ClusterRole
  name: gedge-front-server-role
  apiGroup: ""  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gedge-front-server-admin-role-binding
subjects:
- kind: ServiceAccount
  name: gedge-front-server-account
  namespace: gedge-system
roleRef:
  kind: ClusterRole
  name: admin 
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: gedge-front-server-pod
  namespace: gedge-system
  labels:
    app: gedge-front-server
spec:
  serviceAccount: gedge-front-server-account
  containers:
  - name: gedge-front-server-container
    image: dockereyes/gedge-front-server
    ports:
    - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: gedge-front-server-service
  namespace: gedge-system
spec:
  type: LoadBalancer
  selector:
    app: gedge-front-server
  ports:
    - protocol: TCP
      port: 8787
      targetPort: 8787
